# Generated by Django 2.1.5 on 2019-01-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=24)),
                ('school', models.CharField(choices=[('sc01', '第一中学'), ('sc02', '第二中学'), ('sc03', '第三中学')], max_length=32)),
                ('sfid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('emial', models.EmailField(blank=True, max_length=254, null=True)),
            #     this is a git test word
            #     1
            ],
        ),
    ]
